In [1]:
import torch
import torch.optim as optim
import matplotlib.pyplot as plt
from tqdm import tqdm

import torch
print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))  # Only if device_count > 0

train_loader = torch.load('train_dataloader_aug.pth', weights_only=False)
test_loader = torch.load('test_dataloader_aug.pth', weights_only=False)

True
1
NVIDIA GeForce RTX 2060


In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class EmotionRecognition(nn.Module):
    def __init__(self):
        super(EmotionRecognition, self).__init__()

        # Convolutional Block 1
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(32)

        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(64)

        # Convolutional Block 2
        self.conv3 = nn.Conv2d(64, 64, kernel_size=3, padding=1)
        self.bn3 = nn.BatchNorm2d(64)

        self.conv4 = nn.Conv2d(64, 64, kernel_size=3, padding=1)
        self.bn4 = nn.BatchNorm2d(64)

        self.pool = nn.MaxPool2d(2, 2)
        self.dropout = nn.Dropout(0.2)

        # Dummy input to determine flatten size after conv layers
        with torch.no_grad():
            dummy = torch.zeros(1, 3, 48, 48)
            dummy = self._forward_conv(dummy)
            self.flattened_size = dummy.view(1, -1).size(1)

        self.fc1 = nn.Linear(self.flattened_size, 512)
        self.fc2 = nn.Linear(512, 7)

    def _forward_conv(self, x):
        # Only the convolutional part, used for shape inference and forward
        x = F.relu(self.bn1(self.conv1(x)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = self.pool(x)

        x = F.relu(self.bn3(self.conv3(x)))
        x = F.relu(self.bn4(self.conv4(x)))
        x = self.pool(x)
        return x

    def forward(self, x):
        x = self._forward_conv(x)
        x = torch.flatten(x, 1)
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)
        return x


In [3]:
class FocalLoss(nn.Module):
    def __init__(self, alpha=None, gamma=2.0, reduction='mean'):
        """
        alpha: tensor of shape (num_classes,) for class weights
        gamma: focusing parameter
        """
        super(FocalLoss, self).__init__()
        self.alpha = alpha  # class weights
        self.gamma = gamma
        self.reduction = reduction

    def forward(self, inputs, targets):
        ce_loss = F.cross_entropy(inputs, targets, reduction='none', weight=self.alpha)
        pt = torch.exp(-ce_loss)  # pt = probability of the true class
        focal_loss = (1 - pt) ** self.gamma * ce_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        elif self.reduction == 'sum':
            return focal_loss.sum()
        else:
            return focal_loss

In [4]:
import torch
import torch.optim as optim
from tqdm import tqdm
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.manual_seed(42)
if device.type == "cuda":
    torch.cuda.manual_seed(42)
print(f"Using device: {device}")
model = EmotionRecognition().to(device)
from torch.optim.lr_scheduler import StepLR
import torch.nn as nn

class_weights = compute_class_weight(class_weight='balanced',
                                     classes=np.unique(train_loader.dataset.targets),
                                     y=train_loader.dataset.targets)
class_weights_tensor = torch.tensor(class_weights, dtype=torch.float).to(device)

criterion = FocalLoss(alpha=class_weights_tensor, gamma=1.5)
optimizer = optim.Adam(model.parameters(), lr=0.002, weight_decay=1e-4)
scheduler = StepLR(optimizer, step_size=10, gamma=0.5)

scaler = torch.cuda.amp.GradScaler() if device.type == "cuda" else None



Using device: cuda


C:\Users\Korisnik\AppData\Local\Temp\ipykernel_10624\1828967484.py:25: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler() if device.type == "cuda" else None


In [5]:
def train_one_epoch(model, loader, optimizer, criterion, scaler):
    model.train()
    total_loss, total_correct, total_samples = 0, 0, 0

    for images, labels in tqdm(loader, desc="Training", leave=False):
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()

        with torch.cuda.amp.autocast(enabled=scaler is not None):
            outputs = model(images)
            loss = criterion(outputs, labels)

        if scaler:
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
        else:
            loss.backward()
            optimizer.step()

        total_loss += loss.item() * images.size(0)
        _, predicted = torch.max(outputs, 1)
        total_correct += (predicted == labels).sum().item()
        total_samples += labels.size(0)

    return total_loss / total_samples, 100. * total_correct / total_samples

def evaluate(model, loader):
    model.eval()
    all_preds, all_labels = [], []

    with torch.no_grad():
        for images, labels in loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs, 1)
            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    return np.array(all_labels), np.array(all_preds)

In [7]:
best_loss = float('inf')
patience = 10
epochs_no_improve = 0
num_epochs = 100
save_path = "best_model.pth"

for epoch in range(num_epochs):
    train_loss, train_acc = train_one_epoch(model, train_loader, optimizer, criterion, scaler)
    labels, preds = evaluate(model, test_loader)
    test_acc = 100. * np.sum(preds == labels) / len(labels)

    scheduler.step()

    print(f"\nEpoch {epoch+1}/{num_epochs}")
    print(f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.2f}% | Test Acc: {test_acc:.2f}%")
    print(f"Learning Rate: {scheduler.get_last_lr()[0]:.6f}")

    # Early stopping
    if train_loss < best_loss:
        best_loss = train_loss
        epochs_no_improve = 0
        torch.save(model.state_dict(), save_path)
        print("✅ Saved new best model.")
    else:
        epochs_no_improve += 1
        if epochs_no_improve >= patience:
            print("⏹ Early stopping triggered.")
            break

Training:   0%|          | 0/449 [00:00<?, ?it/s]C:\Users\Korisnik\AppData\Local\Temp\ipykernel_10624\4020488208.py:10: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=scaler is not None):



Epoch 1/100
Train Loss: 1.4973, Train Acc: 18.12% | Test Acc: 21.82%
Learning Rate: 0.002000
✅ Saved new best model.



Epoch 2/100
Train Loss: 1.4587, Train Acc: 20.50% | Test Acc: 22.46%
Learning Rate: 0.002000
✅ Saved new best model.



Epoch 3/100
Train Loss: 1.4428, Train Acc: 20.37% | Test Acc: 24.37%
Learning Rate: 0.002000
✅ Saved new best model.



Epoch 4/100
Train Loss: 1.4284, Train Acc: 18.65% | Test Acc: 17.05%
Learning Rate: 0.002000
✅ Saved new best model.



Epoch 5/100
Train Loss: 1.4182, Train Acc: 14.25% | Test Acc: 22.19%
Learning Rate: 0.002000
✅ Saved new best model.



Epoch 6/100
Train Loss: 1.3958, Train Acc: 16.16% | Test Acc: 20.05%
Learning Rate: 0.002000
✅ Saved new best model.



Epoch 7/100
Train Loss: 1.3778, Train Acc: 17.06% | Test Acc: 20.41%
Learning Rate: 0.002000
✅ Saved new best model.



Epoch 8/100
Train Loss: 1.3622, Train Acc: 19.65% | Test Acc: 20.01%
Learning Rate: 0.002000
✅ Saved new best model.



Epoch 9/100
Train Loss: 1.3561, Train Acc: 21.05% | Test Acc: 28.36%
Learning Rate: 0.002000
✅ Saved new best model.



Epoch 10/100
Train Loss: 1.3390, Train Acc: 23.54% | Test Acc: 29.66%
Learning Rate: 0.001000
✅ Saved new best model.



Epoch 11/100
Train Loss: 1.2699, Train Acc: 28.75% | Test Acc: 39.38%
Learning Rate: 0.001000
✅ Saved new best model.



Epoch 12/100
Train Loss: 1.1913, Train Acc: 33.53% | Test Acc: 36.93%
Learning Rate: 0.001000
✅ Saved new best model.



Epoch 13/100
Train Loss: 1.1453, Train Acc: 35.82% | Test Acc: 44.19%
Learning Rate: 0.001000
✅ Saved new best model.



Epoch 14/100
Train Loss: 1.0968, Train Acc: 38.36% | Test Acc: 46.28%
Learning Rate: 0.001000
✅ Saved new best model.



Epoch 15/100
Train Loss: 1.0640, Train Acc: 40.00% | Test Acc: 47.23%
Learning Rate: 0.001000
✅ Saved new best model.



Epoch 16/100
Train Loss: 1.0276, Train Acc: 42.69% | Test Acc: 46.20%
Learning Rate: 0.001000
✅ Saved new best model.



Epoch 17/100
Train Loss: 0.9973, Train Acc: 43.70% | Test Acc: 48.44%
Learning Rate: 0.001000
✅ Saved new best model.



Epoch 18/100
Train Loss: 0.9638, Train Acc: 44.93% | Test Acc: 46.49%
Learning Rate: 0.001000
✅ Saved new best model.



Epoch 19/100
Train Loss: 0.9412, Train Acc: 45.58% | Test Acc: 50.04%
Learning Rate: 0.001000
✅ Saved new best model.



Epoch 20/100
Train Loss: 0.9280, Train Acc: 47.07% | Test Acc: 50.22%
Learning Rate: 0.000500
✅ Saved new best model.



Epoch 21/100
Train Loss: 0.8647, Train Acc: 49.37% | Test Acc: 52.37%
Learning Rate: 0.000500
✅ Saved new best model.



Epoch 22/100
Train Loss: 0.8403, Train Acc: 50.07% | Test Acc: 53.20%
Learning Rate: 0.000500
✅ Saved new best model.



Epoch 23/100
Train Loss: 0.8218, Train Acc: 50.95% | Test Acc: 54.01%
Learning Rate: 0.000500
✅ Saved new best model.



Epoch 24/100
Train Loss: 0.7960, Train Acc: 51.37% | Test Acc: 55.15%
Learning Rate: 0.000500
✅ Saved new best model.



Epoch 25/100
Train Loss: 0.7783, Train Acc: 52.53% | Test Acc: 54.96%
Learning Rate: 0.000500
✅ Saved new best model.



Epoch 26/100
Train Loss: 0.7674, Train Acc: 52.65% | Test Acc: 55.07%
Learning Rate: 0.000500
✅ Saved new best model.



Epoch 27/100
Train Loss: 0.7571, Train Acc: 53.01% | Test Acc: 54.53%
Learning Rate: 0.000500
✅ Saved new best model.



Epoch 28/100
Train Loss: 0.7522, Train Acc: 53.60% | Test Acc: 55.17%
Learning Rate: 0.000500
✅ Saved new best model.



Epoch 29/100
Train Loss: 0.7268, Train Acc: 54.10% | Test Acc: 55.14%
Learning Rate: 0.000500
✅ Saved new best model.



Epoch 30/100
Train Loss: 0.7244, Train Acc: 54.32% | Test Acc: 54.42%
Learning Rate: 0.000250
✅ Saved new best model.



Epoch 31/100
Train Loss: 0.6896, Train Acc: 55.59% | Test Acc: 57.43%
Learning Rate: 0.000250
✅ Saved new best model.



Epoch 32/100
Train Loss: 0.6728, Train Acc: 56.20% | Test Acc: 56.27%
Learning Rate: 0.000250
✅ Saved new best model.



Epoch 33/100
Train Loss: 0.6646, Train Acc: 56.59% | Test Acc: 56.77%
Learning Rate: 0.000250
✅ Saved new best model.



Epoch 34/100
Train Loss: 0.6602, Train Acc: 56.76% | Test Acc: 57.22%
Learning Rate: 0.000250
✅ Saved new best model.



Epoch 35/100
Train Loss: 0.6432, Train Acc: 57.51% | Test Acc: 56.77%
Learning Rate: 0.000250
✅ Saved new best model.



Epoch 36/100
Train Loss: 0.6450, Train Acc: 57.29% | Test Acc: 57.82%
Learning Rate: 0.000250



Epoch 37/100
Train Loss: 0.6320, Train Acc: 57.94% | Test Acc: 57.82%
Learning Rate: 0.000250
✅ Saved new best model.



Epoch 38/100
Train Loss: 0.6348, Train Acc: 57.34% | Test Acc: 57.62%
Learning Rate: 0.000250



Epoch 39/100
Train Loss: 0.6220, Train Acc: 58.20% | Test Acc: 57.59%
Learning Rate: 0.000250
✅ Saved new best model.



Epoch 40/100
Train Loss: 0.6166, Train Acc: 58.31% | Test Acc: 58.07%
Learning Rate: 0.000125
✅ Saved new best model.



Epoch 41/100
Train Loss: 0.6013, Train Acc: 58.97% | Test Acc: 58.09%
Learning Rate: 0.000125
✅ Saved new best model.



Epoch 42/100
Train Loss: 0.6030, Train Acc: 59.49% | Test Acc: 58.26%
Learning Rate: 0.000125



Epoch 43/100
Train Loss: 0.5873, Train Acc: 59.78% | Test Acc: 57.90%
Learning Rate: 0.000125
✅ Saved new best model.



Epoch 44/100
Train Loss: 0.5791, Train Acc: 60.21% | Test Acc: 58.02%
Learning Rate: 0.000125
✅ Saved new best model.



Epoch 45/100
Train Loss: 0.5787, Train Acc: 59.89% | Test Acc: 58.54%
Learning Rate: 0.000125
✅ Saved new best model.



Epoch 46/100
Train Loss: 0.5712, Train Acc: 60.23% | Test Acc: 58.80%
Learning Rate: 0.000125
✅ Saved new best model.



Epoch 47/100
Train Loss: 0.5776, Train Acc: 60.36% | Test Acc: 58.51%
Learning Rate: 0.000125



Epoch 48/100
Train Loss: 0.5668, Train Acc: 60.41% | Test Acc: 58.75%
Learning Rate: 0.000125
✅ Saved new best model.



Epoch 49/100
Train Loss: 0.5734, Train Acc: 60.21% | Test Acc: 58.92%
Learning Rate: 0.000125



Epoch 50/100
Train Loss: 0.5655, Train Acc: 60.56% | Test Acc: 59.04%
Learning Rate: 0.000063
✅ Saved new best model.



Epoch 51/100
Train Loss: 0.5571, Train Acc: 61.17% | Test Acc: 59.32%
Learning Rate: 0.000063
✅ Saved new best model.



Epoch 52/100
Train Loss: 0.5464, Train Acc: 61.42% | Test Acc: 58.72%
Learning Rate: 0.000063
✅ Saved new best model.



Epoch 53/100
Train Loss: 0.5545, Train Acc: 61.36% | Test Acc: 59.49%
Learning Rate: 0.000063



Epoch 54/100
Train Loss: 0.5501, Train Acc: 61.02% | Test Acc: 59.36%
Learning Rate: 0.000063



Epoch 55/100
Train Loss: 0.5455, Train Acc: 61.55% | Test Acc: 59.03%
Learning Rate: 0.000063
✅ Saved new best model.



Epoch 56/100
Train Loss: 0.5450, Train Acc: 61.70% | Test Acc: 58.89%
Learning Rate: 0.000063
✅ Saved new best model.



Epoch 57/100
Train Loss: 0.5378, Train Acc: 61.82% | Test Acc: 59.38%
Learning Rate: 0.000063
✅ Saved new best model.



Epoch 58/100
Train Loss: 0.5388, Train Acc: 62.04% | Test Acc: 59.25%
Learning Rate: 0.000063



Epoch 59/100
Train Loss: 0.5357, Train Acc: 62.10% | Test Acc: 58.96%
Learning Rate: 0.000063
✅ Saved new best model.



Epoch 60/100
Train Loss: 0.5351, Train Acc: 62.03% | Test Acc: 58.93%
Learning Rate: 0.000031
✅ Saved new best model.



Epoch 61/100
Train Loss: 0.5307, Train Acc: 62.01% | Test Acc: 59.14%
Learning Rate: 0.000031
✅ Saved new best model.



Epoch 62/100
Train Loss: 0.5269, Train Acc: 62.36% | Test Acc: 59.32%
Learning Rate: 0.000031
✅ Saved new best model.



Epoch 63/100
Train Loss: 0.5319, Train Acc: 62.27% | Test Acc: 58.80%
Learning Rate: 0.000031



Epoch 64/100
Train Loss: 0.5286, Train Acc: 62.14% | Test Acc: 59.31%
Learning Rate: 0.000031



Epoch 65/100
Train Loss: 0.5255, Train Acc: 62.56% | Test Acc: 59.04%
Learning Rate: 0.000031
✅ Saved new best model.



Epoch 66/100
Train Loss: 0.5219, Train Acc: 62.60% | Test Acc: 58.89%
Learning Rate: 0.000031
✅ Saved new best model.



Epoch 67/100
Train Loss: 0.5250, Train Acc: 62.13% | Test Acc: 58.89%
Learning Rate: 0.000031



Epoch 68/100
Train Loss: 0.5185, Train Acc: 62.61% | Test Acc: 58.72%
Learning Rate: 0.000031
✅ Saved new best model.



Epoch 69/100
Train Loss: 0.5243, Train Acc: 62.69% | Test Acc: 59.10%
Learning Rate: 0.000031



Epoch 70/100
Train Loss: 0.5268, Train Acc: 62.48% | Test Acc: 59.04%
Learning Rate: 0.000016



Epoch 71/100
Train Loss: 0.5163, Train Acc: 62.69% | Test Acc: 58.92%
Learning Rate: 0.000016
✅ Saved new best model.



Epoch 72/100
Train Loss: 0.5210, Train Acc: 62.93% | Test Acc: 59.14%
Learning Rate: 0.000016



Epoch 73/100
Train Loss: 0.5162, Train Acc: 62.63% | Test Acc: 59.25%
Learning Rate: 0.000016
✅ Saved new best model.



Epoch 74/100
Train Loss: 0.5183, Train Acc: 62.68% | Test Acc: 59.42%
Learning Rate: 0.000016



Epoch 75/100
Train Loss: 0.5137, Train Acc: 63.10% | Test Acc: 59.17%
Learning Rate: 0.000016
✅ Saved new best model.



Epoch 76/100
Train Loss: 0.5144, Train Acc: 62.68% | Test Acc: 59.38%
Learning Rate: 0.000016



Epoch 77/100
Train Loss: 0.5149, Train Acc: 62.69% | Test Acc: 59.39%
Learning Rate: 0.000016



Epoch 78/100
Train Loss: 0.5126, Train Acc: 63.04% | Test Acc: 59.15%
Learning Rate: 0.000016
✅ Saved new best model.



Epoch 79/100
Train Loss: 0.5130, Train Acc: 62.97% | Test Acc: 59.43%
Learning Rate: 0.000016



Epoch 80/100
Train Loss: 0.5108, Train Acc: 62.85% | Test Acc: 59.24%
Learning Rate: 0.000008
✅ Saved new best model.



Epoch 81/100
Train Loss: 0.5133, Train Acc: 62.85% | Test Acc: 59.36%
Learning Rate: 0.000008



Epoch 82/100
Train Loss: 0.5119, Train Acc: 62.85% | Test Acc: 59.06%
Learning Rate: 0.000008



Epoch 83/100
Train Loss: 0.5159, Train Acc: 62.56% | Test Acc: 59.28%
Learning Rate: 0.000008



Epoch 84/100
Train Loss: 0.5142, Train Acc: 62.62% | Test Acc: 59.25%
Learning Rate: 0.000008



Epoch 85/100
Train Loss: 0.5128, Train Acc: 62.58% | Test Acc: 59.38%
Learning Rate: 0.000008



Epoch 86/100
Train Loss: 0.5103, Train Acc: 63.19% | Test Acc: 59.29%
Learning Rate: 0.000008
✅ Saved new best model.



Epoch 87/100
Train Loss: 0.5162, Train Acc: 62.53% | Test Acc: 59.32%
Learning Rate: 0.000008



Epoch 88/100
Train Loss: 0.5118, Train Acc: 62.98% | Test Acc: 59.39%
Learning Rate: 0.000008



Epoch 89/100
Train Loss: 0.5045, Train Acc: 63.41% | Test Acc: 59.32%
Learning Rate: 0.000008
✅ Saved new best model.



Epoch 90/100
Train Loss: 0.5114, Train Acc: 63.05% | Test Acc: 59.42%
Learning Rate: 0.000004



Epoch 91/100
Train Loss: 0.5098, Train Acc: 62.83% | Test Acc: 59.57%
Learning Rate: 0.000004



Epoch 92/100
Train Loss: 0.5108, Train Acc: 63.44% | Test Acc: 59.35%
Learning Rate: 0.000004



Epoch 93/100
Train Loss: 0.5132, Train Acc: 63.05% | Test Acc: 59.33%
Learning Rate: 0.000004



Epoch 94/100
Train Loss: 0.5079, Train Acc: 63.14% | Test Acc: 59.42%
Learning Rate: 0.000004



Epoch 95/100
Train Loss: 0.5086, Train Acc: 63.30% | Test Acc: 59.64%
Learning Rate: 0.000004



Epoch 96/100
Train Loss: 0.5056, Train Acc: 63.49% | Test Acc: 59.53%
Learning Rate: 0.000004



Epoch 97/100
Train Loss: 0.5129, Train Acc: 62.84% | Test Acc: 59.38%
Learning Rate: 0.000004



Epoch 98/100
Train Loss: 0.5040, Train Acc: 63.29% | Test Acc: 59.50%
Learning Rate: 0.000004
✅ Saved new best model.



Epoch 99/100
Train Loss: 0.5053, Train Acc: 63.12% | Test Acc: 59.47%
Learning Rate: 0.000004



Epoch 100/100
Train Loss: 0.5109, Train Acc: 63.37% | Test Acc: 59.33%
Learning Rate: 0.000002


In [8]:
from sklearn.metrics import classification_report, confusion_matrix

# Final evaluation
model.load_state_dict(torch.load(save_path))
model.eval()
labels, preds = evaluate(model, test_loader)

emotion_labels = ['Angry', 'Disgust', 'Fear', 'Happy', 'Sad', 'Surprise', 'Neutral']
print("\nClassification Report:")
print(classification_report(labels, preds, target_names=emotion_labels))
print("Confusion Matrix:")
print(confusion_matrix(labels, preds))


Classification Report:
              precision    recall  f1-score   support

       Angry       0.49      0.54      0.51       958
     Disgust       0.59      0.68      0.63       111
        Fear       0.42      0.36      0.39      1024
       Happy       0.87      0.73      0.80      1774
         Sad       0.55      0.60      0.57      1233
    Surprise       0.45      0.47      0.46      1247
     Neutral       0.70      0.82      0.76       831

    accuracy                           0.60      7178
   macro avg       0.58      0.60      0.59      7178
weighted avg       0.60      0.60      0.60      7178

Confusion Matrix:
[[ 519   22  116   33   91  147   30]
 [  19   75    5    2    2    7    1]
 [ 145    6  369   24  125  218  137]
 [ 101    3   55 1300  145  105   65]
 [  95    7   79   61  739  223   29]
 [ 161   10  188   45  232  587   24]
 [  21    4   63   25   16   20  682]]
