In [1]:
from cnn_model_2 import EmotionRecognition

In [2]:
import torch
import torch.optim as optim
import matplotlib.pyplot as plt
from tqdm import tqdm

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cuda


In [3]:
train_loader = torch.load('train_dataloader.pth')
test_loader = torch.load('test_dataloader.pth')

C:\Users\Korisnik\AppData\Local\Temp\ipykernel_1050720\3212086309.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  train_loader = torch.load('train_dataloader.pth')
C:\Us

In [4]:
model = EmotionRecognition().to(device)

In [7]:
from torch.optim.lr_scheduler import StepLR
import torch.nn as nn
loss_fn = torch.nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

patience = 5  # Number of epochs with no improvement before stopping
best_loss = float('inf')  # Initialize best loss to a very high value
epochs_without_improvement = 0  # Counter for patience

scheduler = StepLR(optimizer, step_size=5, gamma=0.1)
num_epochs = 30

for epoch in range(num_epochs):
    model.train()  # Set model to training mode
    running_loss = 0.0
    correct_predictions = 0
    total_samples = 0

    for images, labels in tqdm(train_loader, desc=f"Epoch {epoch+1}/{num_epochs}", ncols=100):  # Assuming train_loader is defined
        images, labels = images.to(device), labels.to(device)

        # Zero gradients, perform a backward pass, and update weights
        optimizer.zero_grad()

        # Forward pass
        outputs = model(images)
        loss = loss_fn(outputs, labels)

        # Backward pass and optimize
        loss.backward()
        optimizer.step()

        # Update the running loss
        running_loss += loss.item() * images.size(0)

        # Calculate accuracy
        _, predicted = torch.max(outputs, 1)
        correct_predictions += (predicted == labels).sum().item()
        total_samples += labels.size(0)

    # Step the learning rate scheduler
    scheduler.step()

    # Print statistics
    epoch_loss = running_loss / total_samples
    epoch_accuracy = correct_predictions / total_samples * 100

    print(f"Epoch [{epoch + 1}/{num_epochs}], Loss: {epoch_loss:.4f}, Accuracy: {epoch_accuracy:.2f}%")
    print(f"Learning Rate: {scheduler.get_last_lr()[0]:.6f}")  # Print the current learning rate


Epoch 1/30: 100%|█████████████████████████████████████████████████| 449/449 [02:16<00:00,  3.28it/s]


Epoch [1/30], Loss: 1.4106, Accuracy: 46.21%
Learning Rate: 0.001000


Epoch 2/30: 100%|█████████████████████████████████████████████████| 449/449 [00:21<00:00, 21.04it/s]


Epoch [2/30], Loss: 1.2681, Accuracy: 51.69%
Learning Rate: 0.001000


Epoch 3/30: 100%|█████████████████████████████████████████████████| 449/449 [00:21<00:00, 20.64it/s]


Epoch [3/30], Loss: 1.1594, Accuracy: 56.36%
Learning Rate: 0.001000


Epoch 4/30: 100%|█████████████████████████████████████████████████| 449/449 [00:21<00:00, 20.61it/s]


Epoch [4/30], Loss: 1.0477, Accuracy: 60.68%
Learning Rate: 0.001000


Epoch 5/30: 100%|█████████████████████████████████████████████████| 449/449 [00:21<00:00, 20.63it/s]


Epoch [5/30], Loss: 0.9407, Accuracy: 65.03%
Learning Rate: 0.000100


Epoch 6/30: 100%|█████████████████████████████████████████████████| 449/449 [00:22<00:00, 20.31it/s]


Epoch [6/30], Loss: 0.7394, Accuracy: 73.23%
Learning Rate: 0.000100


Epoch 7/30: 100%|█████████████████████████████████████████████████| 449/449 [00:22<00:00, 20.00it/s]


Epoch [7/30], Loss: 0.6946, Accuracy: 74.71%
Learning Rate: 0.000100


Epoch 8/30: 100%|█████████████████████████████████████████████████| 449/449 [03:47<00:00,  1.97it/s]


Epoch [8/30], Loss: 0.6665, Accuracy: 76.22%
Learning Rate: 0.000100


Epoch 9/30: 100%|█████████████████████████████████████████████████| 449/449 [00:58<00:00,  7.64it/s]


Epoch [9/30], Loss: 0.6358, Accuracy: 77.16%
Learning Rate: 0.000100


Epoch 10/30: 100%|████████████████████████████████████████████████| 449/449 [00:21<00:00, 21.07it/s]


Epoch [10/30], Loss: 0.6079, Accuracy: 78.01%
Learning Rate: 0.000010


Epoch 11/30: 100%|████████████████████████████████████████████████| 449/449 [00:21<00:00, 20.62it/s]


Epoch [11/30], Loss: 0.5797, Accuracy: 79.39%
Learning Rate: 0.000010


Epoch 12/30: 100%|████████████████████████████████████████████████| 449/449 [00:21<00:00, 20.54it/s]


Epoch [12/30], Loss: 0.5768, Accuracy: 79.53%
Learning Rate: 0.000010


Epoch 13/30: 100%|████████████████████████████████████████████████| 449/449 [00:21<00:00, 20.55it/s]


Epoch [13/30], Loss: 0.5734, Accuracy: 79.87%
Learning Rate: 0.000010


Epoch 14/30: 100%|████████████████████████████████████████████████| 449/449 [00:21<00:00, 20.55it/s]


Epoch [14/30], Loss: 0.5713, Accuracy: 79.67%
Learning Rate: 0.000010


Epoch 15/30: 100%|████████████████████████████████████████████████| 449/449 [00:21<00:00, 20.51it/s]


Epoch [15/30], Loss: 0.5740, Accuracy: 79.73%
Learning Rate: 0.000001


Epoch 16/30: 100%|████████████████████████████████████████████████| 449/449 [00:21<00:00, 20.59it/s]


Epoch [16/30], Loss: 0.5675, Accuracy: 79.66%
Learning Rate: 0.000001


Epoch 17/30: 100%|████████████████████████████████████████████████| 449/449 [00:21<00:00, 20.54it/s]


Epoch [17/30], Loss: 0.5640, Accuracy: 79.99%
Learning Rate: 0.000001


Epoch 18/30: 100%|████████████████████████████████████████████████| 449/449 [00:21<00:00, 20.92it/s]


Epoch [18/30], Loss: 0.5670, Accuracy: 79.89%
Learning Rate: 0.000001


Epoch 19/30: 100%|████████████████████████████████████████████████| 449/449 [03:46<00:00,  1.99it/s]


Epoch [19/30], Loss: 0.5670, Accuracy: 79.88%
Learning Rate: 0.000001


Epoch 20/30: 100%|████████████████████████████████████████████████| 449/449 [01:03<00:00,  7.03it/s]


Epoch [20/30], Loss: 0.5650, Accuracy: 79.73%
Learning Rate: 0.000000


Epoch 21/30: 100%|████████████████████████████████████████████████| 449/449 [00:21<00:00, 20.50it/s]


Epoch [21/30], Loss: 0.5636, Accuracy: 79.96%
Learning Rate: 0.000000


Epoch 22/30: 100%|████████████████████████████████████████████████| 449/449 [00:21<00:00, 20.42it/s]


Epoch [22/30], Loss: 0.5656, Accuracy: 79.91%
Learning Rate: 0.000000


Epoch 23/30: 100%|████████████████████████████████████████████████| 449/449 [00:22<00:00, 20.30it/s]


Epoch [23/30], Loss: 0.5663, Accuracy: 79.97%
Learning Rate: 0.000000


Epoch 24/30: 100%|████████████████████████████████████████████████| 449/449 [00:21<00:00, 20.44it/s]


Epoch [24/30], Loss: 0.5660, Accuracy: 80.08%
Learning Rate: 0.000000


Epoch 25/30: 100%|████████████████████████████████████████████████| 449/449 [00:22<00:00, 20.34it/s]


Epoch [25/30], Loss: 0.5643, Accuracy: 79.93%
Learning Rate: 0.000000


Epoch 26/30: 100%|████████████████████████████████████████████████| 449/449 [00:22<00:00, 19.99it/s]


Epoch [26/30], Loss: 0.5627, Accuracy: 80.19%
Learning Rate: 0.000000


Epoch 27/30: 100%|████████████████████████████████████████████████| 449/449 [00:22<00:00, 20.18it/s]


Epoch [27/30], Loss: 0.5639, Accuracy: 79.81%
Learning Rate: 0.000000


Epoch 28/30: 100%|████████████████████████████████████████████████| 449/449 [00:22<00:00, 20.40it/s]


Epoch [28/30], Loss: 0.5618, Accuracy: 80.10%
Learning Rate: 0.000000


Epoch 29/30: 100%|████████████████████████████████████████████████| 449/449 [00:21<00:00, 20.56it/s]


Epoch [29/30], Loss: 0.5652, Accuracy: 80.22%
Learning Rate: 0.000000


Epoch 30/30: 100%|████████████████████████████████████████████████| 449/449 [00:22<00:00, 20.40it/s]

Epoch [30/30], Loss: 0.5723, Accuracy: 79.71%
Learning Rate: 0.000000


In [9]:
import torch
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

# Set model to evaluation mode
model.eval()

emotion_labels = ['Angry', 'Disgust', 'Fear', 'Happy', 'Sad', 'Surprise', 'Neutral']


# Containers for predictions and true labels
all_preds = []
all_labels = []

with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)
        _, predicted = torch.max(outputs, 1)

        all_preds.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

# Convert to numpy arrays
all_preds = np.array(all_preds)
all_labels = np.array(all_labels)

# Print classification report
print("Classification Report:")
print(classification_report(all_labels, all_preds, target_names=emotion_labels))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(all_labels, all_preds))

Classification Report:
              precision    recall  f1-score   support

       Angry       0.45      0.46      0.45       958
     Disgust       0.73      0.42      0.54       111
        Fear       0.45      0.39      0.42      1024
       Happy       0.74      0.77      0.75      1774
         Sad       0.50      0.54      0.52      1233
    Surprise       0.43      0.43      0.43      1247
     Neutral       0.74      0.71      0.73       831

    accuracy                           0.56      7178
   macro avg       0.58      0.53      0.55      7178
weighted avg       0.56      0.56      0.56      7178

Confusion Matrix:
[[ 437    6  103   85  132  164   31]
 [  29   47   11    8    5   11    0]
 [ 120    3  403   72  115  207  104]
 [  82    2   56 1372  125  107   30]
 [ 104    4   83  145  664  214   19]
 [ 164    2  148  127  245  539   22]
 [  35    0   88   52   44   22  590]]
